version: '3.7'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
  db:
    container_name: example_db
    image: postgres:9.6.17-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M

  reactive:
    build: ../reactive/.
    ports:
      - '9001:8080'
    environment:
      DB_HOST: example_db
      KAFKA_HOST: kafka
      WAIT_FOR_SAVED_ENTITY: false
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 2000M

  traditional:
    build: ../traditional/.
    ports:
      - '9002:8080'
    environment:
      DB_HOST: example_db
      KAFKA_HOST: kafka
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 2000M
